# data:
train_csv_path: data/diabetic-retinopathy-dataset/train.csv
val_csv_path: data/diabetic-retinopathy-dataset/val.csv

# experiment:
seed: 42
batch_size: 16
num_workers: 2
use_class_weighting: true
use_weighted_sampler: false
model_name: "resnet50"
max_epochs: 20
image_size: 224
learning_rate: 3e-4
use_scheduler: true

logs_dir: logs
checkpoint_dirpath: artifacts/checkpoints
